### ISSUE TITLE
arm64 function not 4-byte aligned: _unwind_tester 

### ISSUE THREAD

**Issue by zelinDavid** [AI-HELP/sdk-ios-example#6]
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/build/Desktop/Packages/aog/ios/official_debug_2017.4.28/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_res_9_ns_parserr", referenced from:
      _query_ip in ElvaChatServiceSDK(ElvaNslookup.o)
  "_res_9_ns_name_uncompress", referenced from:
      _query_ip in ElvaChatServiceSDK(ElvaNslookup.o)
  "_vDSP_mmul", referenced from:
      mat1::dense(float const*, float const*, float const*, int, int, int) in FBSDKCoreKit(FBSDKEventInferencer.o)
      mat1::dense(float const*, float const*, float const*, int, int, int) in FBSDKCoreKit(FBSDKAddressInferencer.o)
  "_res_9_ndestroy", referenced from:
      _query_ip in ElvaChatServiceSDK(ElvaNslookup.o)
  "_res_9_ninit", referenced from:
      _setup_dns_server in ElvaChatServiceSDK(ElvaNslookup.o)
  "_res_9_nquery", referenced from:
      _query_ip in ElvaChatServiceSDK(ElvaNslookup.o)
  "_vDSP_dotpr", referenced from:
      mat1::conv1D(float const*, float const*, int, int, int, int, int) in FBSDKCoreKit(FBSDKEventInferencer.o)
      mat1::conv1D(float const*, float const*, int, int, int, int, int) in FBSDKCoreKit(FBSDKAddressInferencer.o)
  "_res_9_ns_initparse", referenced from:
      _query_ip in ElvaChatServiceSDK(ElvaNslookup.o)
  "_vDSP_vclip", referenced from:
      +[FBSDKEventInferencer predict:viewTree:withLog:] in FBSDKCoreKit(FBSDKEventInferencer.o)
      mat1::predictOnMTML(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mat::MTensor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mat::MTensor> > > const&, float const*) in FBSDKCoreKit(FBSDKEventInferencer.o)
      +[FBSDKAddressInferencer shouldFilterParam:] in FBSDKCoreKit(FBSDKAddressInferencer.o)
      mat1::predictOnMTML(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, char const*, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, mat::MTensor, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, mat::MTensor> > > const&, float const*) in FBSDKCoreKit(FBSDKAddressInferencer.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

麻烦看下正常导入sdk包后编译报此错误。 xcode版本： 11.1 ， 真机编译

**Comment by Joeljt** [comment]
您的问题我们已收到，可以添加微信：lsixjl，我们会帮您解决这个问题哈

**Comment by zelinDavid** [comment]
谢谢，不过都四个多月过去了 我早就解决这个问题了。。。

**Comment by andrazAkeo** [comment]
@zelinDavid I have same problem. how did you solve this problem?

**Comment by zelinDavid** [comment]
在framework下添加 libresolv  和 libresolv9
![image](https://user-images.githubusercontent.com/16894134/158528411-9df34044-4ff5-4057-a199-a680d25f4ba4.png)
